### ISSUE TITLE
Discuss how to deploy website

### ISSUE THREAD

**Issue by jonicious** [CSSclasses/CSSclasses#29]
Because the site is served via Github Pages, we have to use the `gh-pages` branch to push our changes. Building the site is done manually and the build is then pushed to `gh-pages` branch. The `master` branch should always represent the actual site and deploys should be done automatically after you commit to the `master`.

Furthermore, as CSSclasses grows, what do you think about having one or two maintainers per city to become faster in approving pull requests and deploying the site? Of course, code quality is very important, so I would suggest to have multiple reviewers if the pull request is more than fixing a typo.

**Comment by schoenwaldnils** [comment]
Just opened a pull-request to use the new gh-pages-settings.
see #52 
https://github.com/blog/2228-simpler-github-pages-publishing

**Comment by jonicious** [comment]
Now that we are using automatic deployment on master using Travis, I think, we can close this. See b6ecc61
