### ISSUE TITLE
Layout breaks on low viewport height with opened sidebar

### ISSUE THREAD

**Issue by danielberndt** [CSSclasses/CSSclasses#6]
Quite edge case-y, but here's a screen shot if you wanna know what it looks like:

<img width="1059" alt="screen shot 2015-09-20 at 11 50 52" src="https://cloud.githubusercontent.com/assets/856386/9980159/1dd9fc96-5f8e-11e5-8907-61c9a8d6e74a.png">

I assume the sidebar introduces a second scroll layer once the viewport height is too low, causing this issue.

**Comment by radibit** [comment]
Hey @danielberndt @verpixelt :) 

Is this still a valid bug? I tried to reproduce it, but without success.

**Comment by lukaszklis** [comment]
@radibit hasn't seen it for a while, it could be it used to be a bug, however we've solved it in the meantime. Will keep it closed until it pops out again.
