### ISSUE TITLE
JavaScript files not concatinated during deployment process

### ISSUE THREAD

**Issue by lukaszklis** [CSSclasses/CSSclasses#63]
Whenever you make changes to any of the JavaScript source files and merge the changes to master, those files are not being overwritten when delpoying via Travis CI. Initial investigation suggested adding `concat:development` task to the `build` task.

**Comment by jonicious** [comment]
Experienced the same today again 🙄 I think I fixed it in 1f326c5. At least it is working now. Will close it for now. Feel free to re-open this issue when this occurs again.
