### ISSUE TITLE
Theme switcher of code view is confusing

### ISSUE THREAD

**Issue by Dangoo** [CSSclasses/CSSclasses#75]
During the CSSclasses today in Hamburg we got some feedback about the usability of the materials page, specifically the code view and its theme switcher.

## Current behaviour
- First: Non-Coders are not used to dark/light themes or mostly have no preference. So the prominentely placed switcher may confuse ("Why dark/light, whats 'better'?")
- Second: The activated state of the theme switcher (for light theme a white dot in red box) looks more like the learned "empty checkbox". So a click on the assumed "unactive" element has no effect so it seems broken or useless and leads to the feeling of "Am I doing something wrong?"

<img width="697" alt="theme-switcher" src="https://user-images.githubusercontent.com/1252204/30480949-99f1bb1e-9a1c-11e7-9786-5eabb2059da9.png">

## Proposed behaviour
Either the checked state should be inverted or made clearer (hook, dot etc.)

What do you think?

**Comment by jonicious** [comment]
Totally agree! Even as someone who used the materials page a lot I thought that "Dark" is the selected option in your example. I think a dot would make things much clearer (similar to a radio input).

If you come up with a solution, I would be happy to take a look in a pull request! :)
